---
- name: Ensure overlay and br_netfilter modules are loaded
  hosts: jefe
  become: true
  vars_files:
    - /home/ken/Desktop/mine/ansible/env_variables.yaml

  tasks:
    - name: Set up kubeconfig for current user
      ansible.builtin.shell: |
        mkdir -p /home/ken/.kube
        sudo cp -i {{ kubeconfig_path }} $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        executable: /bin/bash

    - name: Wait for Kubernetes API to become available
      ansible.builtin.command: >
        kubectl get --raw=/healthz
      register: kubeapi_health
      retries: 10
      delay: 15
      until: kubeapi_health.rc == 0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Install Flannel CNI
      ansible.builtin.command: >
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/v0.25.1/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"