---
- name: Join worker nodes to Kubernetes cluster
  hosts: workers
  become: true

  tasks:
    - name: Fetch kubeadm join command from master
      delegate_to: jefe
      become: true
      ansible.builtin.slurp:
        src: /home/ken/kubeadm_join_cmd.sh
      register: join_cmd_encoded

    - name: Save join command script to worker node
      ansible.builtin.copy:
        dest: /home/ken/kubeadm_join_cmd.sh
        content: "{{ join_cmd_encoded['content'] | b64decode }}"
        mode: '0755'
        owner: ken
        group: ken

    - name: Execute kubeadm join command
      ansible.builtin.command: /home/ken/kubeadm_join_cmd.sh