---
- name: Ensure overlay and br_netfilter modules are loaded
  hosts: jefe
  become: true
  vars_files:
    - /home/ken/Desktop/mine/ansible/env_variables.yaml

  tasks:
    - name: Check if Kubernetes control plane is already initialized
      ansible.builtin.stat:
        path: "{{ kubeconfig_path }}"
      register: kubeadm_already_run

    - name: Run kubeadm init
      ansible.builtin.command: >
        kubeadm init
        --pod-network-cidr={{ pod_network_cidr }}
        --apiserver-advertise-address={{ ansible_host }}
      when: not kubeadm_already_run.stat.exists
      register: kubeadm_output
      failed_when: "'error' in kubeadm_output.stderr.lower()"

    - name: Save kubeadm join command to file
      when: not kubeadm_already_run.stat.exists
      ansible.builtin.copy:
        dest: "/home/{{ kube_user }}/kubeadm_join_cmd.sh"
        content: |
          #!/bin/bash
          {% for line in kubeadm_output.stdout_lines %}
          {% if line.startswith('kubeadm join') %}
          {{ line }}
          {% endif %}
          {% endfor %}
        mode: '0755'

    - name: Set up kubeconfig for user
      when: not kubeadm_already_run.stat.exists
      become_user: "{{ kube_user }}"
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        cp -i {{ kubeconfig_path }} $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        executable: /bin/bash
