---
- name: Ensure overlay and br_netfilter modules are loaded
  hosts: all
  become: true
  vars_files:
    - /home/ken/Desktop/mine/ansible/env_variables.yaml

  tasks:
    - name: Make sure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes signing key
      ansible.builtin.shell: |
        curl -fsSL {{ kubernetes_apt_key_url }} | gpg --dearmor | tee {{ kubernetes_apt_key_path }} > /dev/null
      args:
        creates: "{{ kubernetes_apt_key_path }}"

    - name: Add Kubernetes apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "{{ kubernetes_apt_repo }}"
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Kubernetes components
      ansible.builtin.apt:
        pkg: "{{ kubernetes_packages }}"
        state: latest

    - name: Hold Kubernetes packages at current version
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ kubernetes_packages }}"