---
- name: Ensure swap is disabled
  hosts: all
  become: true
  vars_files:
    - env_variables
    - vars/vault_pass.yaml

  tasks:
    - name: Debug become password
      ansible.builtin.debug:
        var: ansible_become_pass
      # This will output the value that Ansible 'thinks' is the become password.
      # Be careful, this will expose your password in the output!
      # Only use for debugging and remove immediately after.