---
- name: Ensure swap is disabled
  hosts: all
  become: true
  vars_files:
    - env_variables
    # - vars/vault_pass.yaml
  
  tasks:
    - name: Check if swap is on
      ansible.builtin.shell: cat /proc/swaps
      register: swap_status
      changed_when: false
      failed_when: false # Don't fail if no swap is found (cat /proc/swaps- might exit 1 if file is enpty or not found)

    - name: Disable all active swap
      ansible.builtin.command: swapoff -a
      when: swap_status.stdout | trim != "" # Only run if there's any output from /proc/swaps, indicating active swap
      # swapoff -a is idempotent, so running it even if swap is already off is harmless.
      # The check simply avoids unnecessary command execution.

    - name: Remove swap entry from /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        # Regex to match lines containing "swap swap" that are not commented out
        # and then comments them out.
        regexp: '^\s*([^#\n]+\s+)+swap\s+swap\s+.*$'
        replace: '#\g<0>' # Prepend a '#' to the matched line
        backup: yes # Always a good idea for critical system files
        # This task is idempotent by nature of the replace module


    - name: Ensure no swap file exists
      ansible.builtin.file:
        path: /swapfile
        state: absent
      # This task is idempotent, it will only remove the file if it exists.
