FROM ubuntu:rolling

# Set non-interactive frontend for apt to avoid manual prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update and install dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    openjdk-21-jdk  \
    curl \
    wget \
    gnupg \
    lsb-release \
    ca-certificates \
    software-properties-common



# Add Docker's official GPG key:
RUN apt-get update && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc
    
# Add the repository to Apt sources:
RUN echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io

# Add Jenkins user
RUN useradd -m -d /var/jenkins_home -s /bin/bash jenkins && \
    echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# Give Jenkins user Docker access
RUN usermod -aG docker jenkins

# Install Jenkins
RUN wget -O /usr/share/keyrings/jenkins-keyring.asc \
    https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key && \
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
    https://pkg.jenkins.io/debian-stable binary/ | tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null && \
    apt-get update && apt-get install -y jenkins

# Expose Jenkins port
EXPOSE 8080

# Set Jenkins to run as default user
USER jenkins

# Start Jenkins
CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]