---
- name: Ensure passwordless sudo for ken user
  hosts: all  
  become: true

  tasks:
    - name: Ensure /etc/sudoers.d directory exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'

    - name: Allow ken passwordless sudo via sudoers.d 
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ken
        content: "ken ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'