---
- name: Ensure overlay and br_netfilter modules are loaded
  hosts: all
  become: true
  vars_files:
    - /home/ken/Desktop/mine/ansible/env_variables.yaml

  tasks:
    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker repository for jammy (fallback for oracular)
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
        filename: docker

    - name: Install Docker from Docker's repo
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: true

    - name: Make sure Docker is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Check that /etc/containerd directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate full default containerd config
      ansible.builtin.command: containerd config default
      register: containerd_config
      changed_when: false

    - name: Write full containerd config
      ansible.builtin.copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        mode: '0644'
        backup: true

    - name: Ensure SystemdCgroup is set to true
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*=\s*false'
        replace: '\1SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true