---
- name: Install docker dependencies
  hosts: all
  become: yes

# Update and upgrade the os
  tasks:
  - name: Update and upgrade the nodes
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes

# And then remove unnecessary dependencies
  - name: Remove dependencies that are no longer required.
    ansible.builtin.apt:
      autoremove: yes

# Install required system packages for Docker
  - name: Install required system packages
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - wget
        - gnupg
        - software-properties-common
        - python3
        - python3-pip
        - python3-setuptools
        - virtualenv
      state: latest
      update_cache: true

# Get the GPG apt key
  - name: Add Docker GPG apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

# Get the Docker repository
  - name: Add the Docker repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu oracular stable
      state: present

# Update the local repositories and install docker-ce
  - name: Update apt and install docker.io
    ansible.builtin.apt:
      name: docker.io
      state: latest
      update_cache: true