---
- name: Install Kubernetes
  hosts: all
  become: yes

  tasks:
# DISABLE SWAP SPACE
# The reason is that swap degrades performance since it’s slower for the 
# kernel to access it than RAM. Disabling it ensures consistent application 
# performance without the unpredictability of swap usage.
    - name: Disable swap space on all nodes
      ansible.builtin.shell:
        cmd: sudo swapoff -a

# Enable c-groups so the kubelet will work out of the box.
# Modify the configuration file /boot/firmware/cmdline.txt
# By adding the below options
# cgroup_enable=memory cgroup_memory=1
    - name: Ensure cgroup options exist in cmdline.txt
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: '^(?!.*cgroup_enable=memory cgroup_memory=1)(.*)$'
        line: '\1 cgroup_enable=memory cgroup_memory=1'

    - name: Enable and load overlay and br_netfilter
      ansible.builtin.shell:
        cmd: sudo modprobe overlay && sudo modprobe br_netfilter

    - name: Permanently load the above kernel modules
      ansible.builtin.shell:
        cmd: sudo tee /etc/modules-load.d/k8s.conf <<EOF
              overlay
              br_netfilter
              EOF

# Configure Kubernetes networking so that the pods can communicate with each other
# and the outside environment effortlessly.
    - name: Create the Kubernetes configuration file in /etc/sysctl.d
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        
    - name: Apply sysctl parameters
      ansible.builtin.command: sysctl --system

# Reboot machines 
    - name: Reboot the server.
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"

# Download Kubernetes public signing key and repositories
    - name: Download the public signing key for the Kubernetes package repositories.
      ansible.builtin.shell:
        cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Allow unprivileged APT programs to read this keyring
      ansible.builtin.command: sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add the appropriate Kubernetes apt repository.
      ansible.builtin.shell:
        cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list && sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly

# Update the local repositories
    - name: Update and upgrade the nodes
      ansible.builtin.apt:
        update_cache: yes

    - name: Install kubectl
      ansible.builtin.apt:
        pkg:
          - kubectl
          - kubelet
          - kubeadm

    
