---
- name: Ensure overlay and br_netfilter modules are loaded
  hosts: all
  become: true
  vars_files:
    - /home/ken/Desktop/mine/ansible/env_variables.yaml

  tasks:
    
    - name: Load required kernel modules
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      loop: "{{ kernel_modules_required }}"

    - name: Ensure kernel modules persist at boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          {% for mod in kernel_modules_required %}
          {{ mod }}
          {% endfor %}
        owner: root
        group: root
        mode: '0644'